@startmindmap 04_02_atividades_de_aprendizagem_digitais_centradas_na_desconstrucao_de_imagens_em_movimento
!define LIGHTBLUE
!includeurl https://gist.githubusercontent.com/amgs/de57560012a8a5f0e4240f392b678a40/raw/c903c6b4f16b60b5eef3248f093497faae378f51/style.puml

*:**Atividades de aprendizagem digitais**
**centradas na desconstrução de imagens em movimento**;

left side

**_ permitem inovar 
*** Vídeo educativo
*** Metodologias ativas centradas no estudante
*** Alinhamento curricular
****_ Conteúdos curriculares
****_ Objetivos de aprendizagem
****_ Contexto educativo
*** Interação significativa
****_ Alunos
****_ Professor
*** Metodologias de avaliação
****_ Formativa
****_ Sumativa
****_ Progresso e reflexão
*** Mediação pedagógica
****_ Recursos audiovisuais
****_ Conceção e implementação

right side

**_ estruturadas por
*** Planificação
****_ Escolha do vídeo
*****_ Qualidade técnica
*****_ Pertinência pedagógica
*****_ Adequação ao público-alvo
****_ Preparação de materiais de apoio
*****_ Grelhas de análise
*****_ Recursos complementares
****_ Licenciamento do vídeo
*** Visualização e Análise
****_ Observações guiadas
****_ Análise crítica
****_ Visualização contínua e pausada
****_ Registo e reflexão
*** Debate e Reflexão
****_ Construção de sentido e partilha de interpretações
****_ Análise de aspetos do vídeo
****_ Ligação aos conteúdos da disciplina
****_ Presencial e fóruns digitais
****_ Condições de participação
*****_ Equidade e respeito
****_ Papel do professor
*****_ Moderador
*****_ Feedback contínuo
****_ Desenvolvimento do pensamento crítico
****_ Construção coletiva do conhecimento
*** Conclusão e Avaliação
****_ Tarefas de consolidação
*****_ Criação de narrativas digitais
*****_ Elaboração de jogos educativos
*****_ Projetos colaborativos
****_ Desenvolvimento de competências
*****_ Autonomia
*****_ Resolução de problemas
*****_ Flexibilidade cognitiva
*****_ Trabalho em equipa
****_ Ferramentas digitais
*****_ exemplos
******_ Animaker
******_ WeVideo
****_ Integração pedagógica crítica do vídeo

@endmindmap