@startmindmap 01_03_o_paradigma_da_educomunicacao_conceitos
!define LIGHTBLUE
!includeurl https://gist.githubusercontent.com/amgs/de57560012a8a5f0e4240f392b678a40/raw/c903c6b4f16b60b5eef3248f093497faae378f51/style.puml

* **Conceitos Fundamentais**

left side

**_ Ensino Remoto
***_ <color:grey>Aula em tempo real, mas com distanciamento geográfico.
**_ Ensino à Distância
***_ <color:grey>Distanciamento geográfico e temporal.
**_ Educação à Distância
***_ <color:grey>Enfase na construção e socialização do conhecimento.
**_ e-Learning
***_ <color:grey>Ensino mediado por tecnologias digitais.
**_ Educação Online
***_ <color:grey>Processos completamente reticulares.
right side
**_ Web-based Learning
***_ <color:grey>Aprendizagem suportada pela web.
**_ Open Learning
***_ <color:grey>Foco na autonomia do estudante.
**_ Blended Learning
***_ <color:grey>Combinação de métodos presenciais e à distância.
**_ Educação Híbrida
***_ <color:grey>Integração de culturas analógicas e digitais.
**_ Educação Onlife
***_ <color:grey>Integração das dimensões sociais online e offline.

@endmindmap